# Generated by Django 5.1.7 on 2025-03-25 02:52

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blog.blogcategory'),
        ),
    ]
