# Generated by Django 4.2.20 on 2025-04-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('blog', '0004_blogpage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blog.blogcategory', verbose_name='Danh mục bài viết'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Giới thiệu'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Ảnh đại diện'),
        ),
    ]
