# Generated by Django 4.2.20 on 2025-04-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_categorylistpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylistpage',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
