# Generated by Django 4.2.20 on 2025-04-06 11:31

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_categorylistpage_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylistpage',
            name='category_slug',
        ),
        migrations.AlterField(
            model_name='categorylistpage',
            name='body',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Mô tả danh mục'),
        ),
        migrations.AlterField(
            model_name='categorylistpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_pages', to='blog.blogcategory', verbose_name='Danh mục'),
        ),
    ]
