# Generated by Django 4.2.20 on 2025-04-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='Còn hàng'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='is_sales',
            field=models.BooleanField(default=False, verbose_name='Đang khuyến mãi'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt mua'),
        ),
    ]
